# example (non-exhaustive) psiflow config file for v4.0.0-final
parsl_log_level: INFO
container_uri: 'oras://ghcr.io/molmod/psiflow:v4.0.0-final_cu124'
default_threads: 4
retries: 0

ModelEvaluation:
  cores_per_worker: 4
  gpu: false
  max_simulation_time: 10  # minutes
  slurm:
    # specify what resources Parsl should request from SLURM
    # see the docs for all available options:
    # https://parsl.readthedocs.io/en/stable/stubs/parsl.providers.SlurmProvider.html
    partition: ...
    account: ...
    nodes_per_block: 1
    cores_per_node: 16
    max_blocks: ...
    walltime: ...
    scheduler_options: ...
    worker_init: ...


CP2K:
  cores_per_worker: 32
  max_evaluation_time: 30  # minutes
  # if you want to use the CP2K container, you need to specify a launch command
  # otherwise psiflow will assume that the executable is available on PATH
  launch_command: 'apptainer exec -e --no-init oras://ghcr.io/molmod/cp2k:2024.1 /opt/entry.sh mpirun -bind-to core -np 32 cp2k.psmp'
  slurm:
    ...


